### ISSUE TITLE
Problem white android 

### ISSUE THREAD

**Issue by raysdl9012** [jpnurmi/statusbar#1]
when i build my app, this message : JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
what is the problem?

**Comment by jpnurmi** [comment]
Which device and Android version? The StatusBar implementation is using QtAndroid::runOnAndroidThread() to execute the JNI calls, so I can't say off the top of my head what might go wrong there. Is there any multi-threading involved on the app's side? Where is the StatusBar instance created?

**Comment by jpnurmi** [comment]
Are you able to reproduce the problem with a minimal Qt Quick app?

    // main.qml
    import QtQuick 2.7
    import QtQuick.Window 2.2
    import StatusBar 0.1

    Window {
        visible: true
        StatusBar {
            color: "red"
        }
    }

**Comment by raysdl9012** [comment]
Thanks the problem was, quickcontrols2 and in the main.cpp write  QQuickStyle::setStyle("Material");
and this:

  QtAndroid::runOnAndroidThread([=]() {
        QAndroidJniObject window = QtAndroid::androidActivity().callObjectMethod("getWindow", "()Landroid/view/Window;");
        window.callMethod<void>("addFlags", "(I)V", FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
        window.callMethod<void>("clearFlags", "(I)V", FLAG_TRANSLUCENT_STATUS);
        window.callMethod<void>("setStatusBarColor", "(I)V", color.rgba());
    });

i don't include   QtAndroid::runOnAndroidThread

thanks
