### ISSUE TITLE
Change Text Color statusbar

### ISSUE THREAD

**Issue by raysdl9012** [jpnurmi/statusbar#2]
Can you change the color of text from statusbar?

**Comment by jpnurmi** [comment]
I've added a `StatusBar::theme` property. To be analogous with the Qt Quick Controls 2 Material style, a light theme means dark text on light background, and a dark theme means light text on dark background.

The values of `StatusBar.Theme` and `Material.Theme` enum values are equal, so you can use either `StatusBar.Light`, `StatusBar.Dark`, `Material.Light`, or `Material.Dark` as you wish:

    StatusBar {
        theme: StatusBar.Light // DARK TEXT (assumes LIGHT application theme/background)
    }

vs.

    StatusBar {
        theme: StatusBar.Dark // LIGHT TEXT (assumes DARK application theme/background)
    }

**Comment by raysdl9012** [comment]
Perfect 
Thanks
