### ISSUE TITLE
statusbar.pri question

### ISSUE THREAD

**Issue by ekke** [jpnurmi/statusbar#6]
I studied your code how you're using StatusBar and StatusBarPrivate to provide x-platform solution.
there's one thing I don't understand:
why is inside statusbar.pri no
`HEADERS += \
$$PWD/statusbar_p.h` ?
thx
ekke

**Comment by jpnurmi** [comment]
Looks like an oversight, should be there indeed. :)

**Comment by ekke** [comment]
thx confirming.
